### ISSUE TITLE
make certificates as arguments of the client.get_instance() method.

### ISSUE THREAD

**Issue by AlexeyElizarov** [2cubs/navys-client#2]

**Comment by PandaHugMonster** [comment]
Done (App-level library), **but currently in the experimenting branch with other changes (Branch is broken, don't use the code from it)**. Will appear in development branch in the next version (0.4.0).
Documentation is not done, but will be added to the referenced above version.

Usage example:
```python3

ssl_path = join(dirname(abspath(__file__)), 'ssl_directory')

instance_params = {
	'client_crt': join(ssl_path, 'client.crt'),
	'client_key': join(ssl_path, 'client.key'),
	'server_crt': join(ssl_path, 'server.crt'),
	'server_hostname': '2cubs-server',
}

app = ExampleClient.get_instance(**instance_params)

```
